# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.srcs/sources_1/ip/blk_mem_fin_line/blk_mem_fin_line.xci
# IP: The module: 'blk_mem_fin_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.gen/sources_1/ip/blk_mem_fin_line/blk_mem_fin_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_fin_line'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.srcs/sources_1/ip/blk_mem_fin_line/blk_mem_fin_line.xci
# IP: The module: 'blk_mem_fin_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.gen/sources_1/ip/blk_mem_fin_line/blk_mem_fin_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_fin_line'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
