# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/DDR_MIG_pins.xdc

# XDC: new/BASE_pins.xdc

# XDC: new/SPI_pins.xdc

# XDC: new/UART_pins.xdc

# XDC: new/VGA_pins.xdc

# Block Designs: bd/Block_top/Block_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top || ORIG_REF_NAME==Block_top} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_clk_wiz_0_0/Block_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_clk_wiz_0_0 || ORIG_REF_NAME==Block_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_vector_logic_0_0/Block_top_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_vector_logic_0_0 || ORIG_REF_NAME==Block_top_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_mig_axi_wrapper_0_0/Block_top_mig_axi_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_mig_axi_wrapper_0_0 || ORIG_REF_NAME==Block_top_mig_axi_wrapper_0_0} -quiet] -quiet

# IP: ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_vector_logic_0_1/Block_top_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_vector_logic_0_1 || ORIG_REF_NAME==Block_top_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_smartconnect_0_0/Block_top_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_smartconnect_0_0 || ORIG_REF_NAME==Block_top_smartconnect_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_FLASH_SPI_wrapper_0_0/Block_top_FLASH_SPI_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_FLASH_SPI_wrapper_0_0 || ORIG_REF_NAME==Block_top_FLASH_SPI_wrapper_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_smartconnect_0_1/Block_top_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_smartconnect_0_1 || ORIG_REF_NAME==Block_top_smartconnect_0_1} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_ds_buf_0_0/Block_top_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_ds_buf_0_0 || ORIG_REF_NAME==Block_top_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_axi_quad_spi_0_1/Block_top_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_axi_quad_spi_0_1 || ORIG_REF_NAME==Block_top_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_ds_buf_0_1/Block_top_util_ds_buf_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_ds_buf_0_1 || ORIG_REF_NAME==Block_top_util_ds_buf_0_1} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_ds_buf_0_2/Block_top_util_ds_buf_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_ds_buf_0_2 || ORIG_REF_NAME==Block_top_util_ds_buf_0_2} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_util_ds_buf_2_0/Block_top_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_util_ds_buf_2_0 || ORIG_REF_NAME==Block_top_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_axi_uartlite_0_0/Block_top_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_axi_uartlite_0_0 || ORIG_REF_NAME==Block_top_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_VexiiSocWrapper_0_1/Block_top_VexiiSocWrapper_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_VexiiSocWrapper_0_1 || ORIG_REF_NAME==Block_top_VexiiSocWrapper_0_1} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_xlconcat_0_0/Block_top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_xlconcat_0_0 || ORIG_REF_NAME==Block_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_VDP_0_0/Block_top_VDP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_VDP_0_0 || ORIG_REF_NAME==Block_top_VDP_0_0} -quiet] -quiet

# IP: ip/blk_mem_tile_data/blk_mem_tile_data.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_tile_data || ORIG_REF_NAME==blk_mem_tile_data} -quiet] -quiet

# IP: ip/blk_mem_tile_map/blk_mem_tile_map.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_tile_map || ORIG_REF_NAME==blk_mem_tile_map} -quiet] -quiet

# IP: ip/blk_mem_buf_line/blk_mem_buf_line.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_buf_line || ORIG_REF_NAME==blk_mem_buf_line} -quiet] -quiet

# IP: ip/blk_mem_fin_line/blk_mem_fin_line.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_fin_line || ORIG_REF_NAME==blk_mem_fin_line} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_axi_bram_ctrl_0_0/Block_top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Block_top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Block_top/ip/Block_top_axi_bram_ctrl_map_0/Block_top_axi_bram_ctrl_map_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_top_axi_bram_ctrl_map_0 || ORIG_REF_NAME==Block_top_axi_bram_ctrl_map_0} -quiet] -quiet

# XDC: /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.gen/sources_1/bd/Block_top/Block_top_ooc.xdc
