#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Aug 06 17:27:57 CEST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim Block_Testbench_behav -key {Behavioral:sim_1:Functional:Block_Testbench} -tclbatch Block_Testbench.tcl -protoinst "protoinst_files/bd_797d.protoinst" -protoinst "protoinst_files/bd_b9bc.protoinst" -protoinst "protoinst_files/Block_top.protoinst" -view /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.srcs/sim_1/imports/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/VexiiRV_wrapper_behav.wcfg -log simulate.log"
xsim Block_Testbench_behav -key {Behavioral:sim_1:Functional:Block_Testbench} -tclbatch Block_Testbench.tcl -protoinst "protoinst_files/bd_797d.protoinst" -protoinst "protoinst_files/bd_b9bc.protoinst" -protoinst "protoinst_files/Block_top.protoinst" -view /home/lovro/ARES/ARES_fpga/ARES_fpga/ARES_fpga.srcs/sim_1/imports/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/VexiiRV_wrapper_behav.wcfg -log simulate.log

