# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0.xci
# IP: The module: 'Block_top_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0.xci
# IP: The module: 'Block_top_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_clk_wiz_1_0/Block_top_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
