# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/bd/Block_top/ip/Block_top_mig_axi_wrapper_0_0/Block_top_mig_axi_wrapper_0_0.xci
# IP: The module: 'Block_top_mig_axi_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_mig_axi_wrapper_0_0/Block_top_mig_axi_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_mig_axi_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/bd/Block_top/ip/Block_top_mig_axi_wrapper_0_0/Block_top_mig_axi_wrapper_0_0.xci
# IP: The module: 'Block_top_mig_axi_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/lovro/Documents/Alchistry_Labs/DDR3 test/cores/Alchitry AMIX_RISCV/Alchitry AMIX_RISCV.gen/sources_1/bd/Block_top/ip/Block_top_mig_axi_wrapper_0_0/Block_top_mig_axi_wrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_top_mig_axi_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
