set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]

set_property PACKAGE_PIN N14 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# clk => 100000000Hz
create_clock -period 10.000 -name clk_0 -waveform {0.000 5.000} [get_ports clk]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks clk_0]

set_property PACKAGE_PIN P6 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN K13 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]

set_property PACKAGE_PIN K12 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]

set_property PACKAGE_PIN L14 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]

set_property PACKAGE_PIN L13 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]

set_property PACKAGE_PIN M15 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]

set_property PACKAGE_PIN M14 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]

set_property PACKAGE_PIN M12 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]

set_property PACKAGE_PIN P14 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]




set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports {ddr3_addr[0]}]
set_property LOAD 5 [get_ports {ddr3_addr[10]}]
set_property LOAD 5 [get_ports {ddr3_addr[11]}]
set_property LOAD 5 [get_ports {ddr3_addr[12]}]
set_property LOAD 5 [get_ports {ddr3_addr[13]}]
set_property LOAD 5 [get_ports {ddr3_addr[1]}]
set_property LOAD 5 [get_ports {ddr3_addr[2]}]
set_property LOAD 5 [get_ports {ddr3_addr[3]}]
set_property LOAD 5 [get_ports {ddr3_addr[4]}]
set_property LOAD 5 [get_ports {ddr3_addr[5]}]
set_property LOAD 5 [get_ports {ddr3_addr[6]}]
set_property LOAD 5 [get_ports {ddr3_addr[7]}]
set_property LOAD 5 [get_ports {ddr3_addr[8]}]
set_property LOAD 5 [get_ports {ddr3_addr[9]}]
set_property LOAD 5 [get_ports {ddr3_ba[0]}]
set_property LOAD 5 [get_ports {ddr3_ba[1]}]
set_property LOAD 5 [get_ports {ddr3_ba[2]}]
set_property LOAD 5 [get_ports ddr3_cas_n]
set_property LOAD 5 [get_ports ddr3_ck_n]
set_property LOAD 5 [get_ports ddr3_ck_p]
set_property LOAD 5 [get_ports ddr3_cke]
set_property LOAD 5 [get_ports ddr3_cs_n]
set_property LOAD 5 [get_ports {ddr3_dm[0]}]
set_property LOAD 5 [get_ports {ddr3_dm[1]}]
set_property LOAD 5 [get_ports {ddr3_dq[0]}]
set_property LOAD 5 [get_ports {ddr3_dq[10]}]
set_property LOAD 5 [get_ports {ddr3_dq[11]}]
set_property LOAD 5 [get_ports {ddr3_dq[12]}]
set_property LOAD 5 [get_ports {ddr3_dq[13]}]
set_property LOAD 5 [get_ports {ddr3_dq[14]}]
set_property LOAD 5 [get_ports {ddr3_dq[15]}]
set_property LOAD 5 [get_ports {ddr3_dq[1]}]
set_property LOAD 5 [get_ports {ddr3_dq[2]}]
set_property LOAD 5 [get_ports {ddr3_dq[3]}]
set_property LOAD 5 [get_ports {ddr3_dq[4]}]
set_property LOAD 5 [get_ports {ddr3_dq[5]}]
set_property LOAD 5 [get_ports {ddr3_dq[6]}]
set_property LOAD 5 [get_ports {ddr3_dq[7]}]
set_property LOAD 5 [get_ports {ddr3_dq[8]}]
set_property LOAD 5 [get_ports {ddr3_dq[9]}]
set_property LOAD 5 [get_ports {ddr3_dqs_n[0]}]
set_property LOAD 5 [get_ports {ddr3_dqs_n[1]}]
set_property LOAD 5 [get_ports {ddr3_dqs_p[0]}]
set_property LOAD 5 [get_ports {ddr3_dqs_p[1]}]
set_property LOAD 5 [get_ports ddr3_odt]
set_property LOAD 5 [get_ports ddr3_ras_n]
set_property LOAD 5 [get_ports ddr3_reset_n]
set_property LOAD 5 [get_ports ddr3_we_n]
set_property LOAD 5 [get_ports {led[0]}]
set_property LOAD 5 [get_ports {led[1]}]
set_property LOAD 5 [get_ports {led[2]}]
set_property LOAD 5 [get_ports {led[3]}]
set_property LOAD 5 [get_ports {led[4]}]
set_property LOAD 5 [get_ports {led[5]}]
set_property LOAD 5 [get_ports {led[6]}]
set_property LOAD 5 [get_ports {led[7]}]
