module VexiiSocWrapper(
  output wire          mBus_awvalid,
  input  wire          mBus_awready,
  output wire [31:0]   mBus_awaddr,
  output wire [7:0]    mBus_awid,
  output wire [7:0]    mBus_awlen,
  output wire [2:0]    mBus_awsize,
  output wire [1:0]    mBus_awburst,
  //output wire          mBus_awallStrb,
  output wire          mBus_wvalid,
  input  wire          mBus_wready,
  output wire [31:0]   mBus_wdata,
  output wire [3:0]    mBus_wstrb,
  output wire          mBus_wlast,
  input  wire          mBus_bvalid,
  output wire          mBus_bready,
  input  wire [7:0]    mBus_bid,
  input  wire [1:0]    mBus_bresp,
  output wire          mBus_arvalid,
  input  wire          mBus_arready,
  output wire [31:0]   mBus_araddr,
  output wire [7:0]    mBus_arid,
  output wire [7:0]    mBus_arlen,
  output wire [2:0]    mBus_arsize,
  output wire [1:0]    mBus_arburst,
  input  wire          mBus_rvalid,
  output wire          mBus_rready,
  input  wire [31:0]   mBus_rdata,
  input  wire [7:0]    mBus_rid,
  input  wire [1:0]    mBus_rresp,
  input  wire          mBus_rlast,

  output wire          pBus_awvalid,
  input  wire          pBus_awready,
  output wire [31:0]   pBus_awaddr,
  output wire [2:0]    pBus_awprot,
  output wire          pBus_wvalid,
  input  wire          pBus_wready,
  output wire [31:0]   pBus_wdata,
  output wire [3:0]    pBus_wstrb,
  input  wire          pBus_bvalid,
  output wire          pBus_bready,
  input  wire [1:0]    pBus_bresp,
  output wire          pBus_arvalid,
  input  wire          pBus_arready,
  output wire [31:0]   pBus_araddr,
  output wire [2:0]    pBus_arprot,
  input  wire          pBus_rvalid,
  output wire          pBus_rready,
  input  wire [31:0]   pBus_rdata,
  input  wire [1:0]    pBus_rresp,

(* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 s_axi_aclk CLK" *)
(* X_INTERFACE_PARAMETER =
   "ASSOCIATED_BUSIF mBus:pBus, ASSOCIATED_RESET s_axi_aresetn, FREQ_HZ 100000000" *)
input wire s_axi_aclk,

(* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 s_axi_aresetn RST" *)
(* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
input wire s_axi_aresetn,
  input  wire [31:0]   peripheral_externalInterrupts_port

);
VexiiSoc Soc
(
  .mBus_awvalid(mBus_awvalid),
  .mBus_awready(mBus_awready),
  .mBus_awaddr(mBus_awaddr),
  .mBus_awid(mBus_awid),
  .mBus_awlen(mBus_awlen),
  .mBus_awsize(mBus_awsize),
  .mBus_awburst(mBus_awburst),
  .mBus_awallStrb(),        //Not needed
  .mBus_wvalid(mBus_wvalid),
  .mBus_wready(mBus_wready),
  .mBus_wdata(mBus_wdata),
  .mBus_wstrb(mBus_wstrb),
  .mBus_wlast(mBus_wlast),
  .mBus_bvalid(mBus_bvalid),
  .mBus_bready(mBus_bready),
  .mBus_bid(mBus_bid),
  .mBus_bresp(mBus_bresp),
  .mBus_arvalid(mBus_arvalid),
  .mBus_arready(mBus_arready),
  .mBus_araddr(mBus_araddr),
  .mBus_arid(mBus_arid),
  .mBus_arlen(mBus_arlen),
  .mBus_arsize(mBus_arsize),
  .mBus_arburst(mBus_arburst),
  .mBus_rvalid(mBus_rvalid),
  .mBus_rready(mBus_rready),
  .mBus_rdata(mBus_rdata),
  .mBus_rid(mBus_rid),
  .mBus_rresp(mBus_rresp),
  .mBus_rlast(mBus_rlast),

  .pBus_awvalid(pBus_awvalid),
  .pBus_awready(pBus_awready),
  .pBus_awaddr(pBus_awaddr),
  .pBus_awprot(pBus_awprot),
  .pBus_wvalid(pBus_wvalid),
  .pBus_wready(pBus_wready),
  .pBus_wdata(pBus_wdata),
  .pBus_wstrb(pBus_wstrb),
  .pBus_bvalid(pBus_bvalid),
  .pBus_bready(pBus_bready),
  .pBus_bresp(pBus_bresp),
  .pBus_arvalid(pBus_arvalid),
  .pBus_arready(pBus_arready),
  .pBus_araddr(pBus_araddr),
  .pBus_arprot(pBus_arprot),
  .pBus_rvalid(pBus_rvalid),
  .pBus_rready(pBus_rready),
  .pBus_rdata(pBus_rdata),
  .pBus_rresp(pBus_rresp),

  .litex_reset(~s_axi_aresetn),
  .litex_clk(s_axi_aclk),
  .peripheral_externalInterrupts_port(peripheral_externalInterrupts_port)
);

endmodule